- name: 'Stop Tomcat'
  command: ./shutdown.sh
  args:
    chdir: /var/lib/tomcat/bin/
  when: "'tomcat' in group_names"

- name: 'Stop Services'
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - "postgresql-9.6"
    - "jira"
    - "confluence"
  when: "'atlassian' in group_names"
  
  