- name: 'set downtime'
  include_role:
    name: my_monitoring_role
  vars:
    - action: set_downtime
    - start_time: start_time
    - end_time: end_time
    - host: {{ ansible_host }}
    - operation: add

- name: 'disable backup'
  include_role:
    name: my_backup_role
  vars:
    - action: disable_backup
    - host: {{ ansible_host }}

- name: 'send_mail'
  include_role:
    name: my_mail_role
  vars:
    - mail_template: maintenance_start
    - recipient: maintenance_recipient@company.com 
  run_once: yes

